// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCrm7DJuGEY_ch2rMWOvJnnerDtaoL4k',
    appId: '1:900923122841:web:d54b6e74e7a33061384408',
    messagingSenderId: '900923122841',
    projectId: 'contact-tracing-3a-2023',
    authDomain: 'contact-tracing-3a-2023.firebaseapp.com',
    storageBucket: 'contact-tracing-3a-2023.appspot.com',
    measurementId: 'G-NRF9GMM5K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpoxaT3vle_-N-vZo0bvNBz3qsr9SZDEo',
    appId: '1:900923122841:android:8287a2173e7a639b384408',
    messagingSenderId: '900923122841',
    projectId: 'contact-tracing-3a-2023',
    storageBucket: 'contact-tracing-3a-2023.appspot.com',
  );
}
